# Generated by Django 2.2.15 on 2020-08-11 10:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventToDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user_properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('event_properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('send_amplitude', models.BooleanField()),
                ('sent_amplitude', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('status_amplitude', models.CharField(max_length=256, null=True)),
                ('send_intercom', models.BooleanField()),
                ('sent_intercom', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('status_intercom', models.CharField(max_length=256, null=True)),
                ('send_user_dot_com', models.BooleanField()),
                ('sent_user_dot_com', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('status_user_dot_com', models.CharField(max_length=256, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
