# Generated by Django 2.2.15 on 2020-08-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtodispatch',
            name='send_mix_panel',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtodispatch',
            name='sent_mix_panel',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventtodispatch',
            name='status_mix_panel',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
