# Generated by Django 3.2.1 on 2021-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dispatcher', '0002_auto_20200818_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtodispatch',
            name='event_properties',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eventtodispatch',
            name='session_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eventtodispatch',
            name='user_properties',
            field=models.JSONField(default=dict),
        ),
    ]
