# Generated by Django 3.2.13 on 2022-07-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dispatcher', '0003_auto_20210510_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtodispatch',
            name='send_ga4',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtodispatch',
            name='sent_ga4',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventtodispatch',
            name='status_ga4',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
